import { onboardingLanguage } from './onboardingCopy';

export const eventMomentCopy = {
  es: {
    featured: 'Momento destacado',
    publishing: 'Publicando…',
    connect: 'Conectar',
    shortVideo: 'Video corto',
    eventVideo: 'Video del evento',
    tapToOpen: 'Toca para abrir',
    imageLoadFailure: 'No pudimos cargar esta foto',
    commentPlaceholder: 'Escribe un comentario',
    sendComment: 'Enviar',
    errorTitle: 'No pudimos guardar la reacción',
    reactionFailure: 'Nada cambió en tu cuenta. Comprueba tu conexión e inténtalo nuevamente.',
    viewPhoto: (authorName: string) => `Ver foto de ${authorName}`,
    openVideo: (authorName: string) => `Abrir video de ${authorName}`,
    sharedPhoto: (authorName: string) => `Foto compartida por ${authorName}`,
    summary: (reactionCount: number, commentCount: number) => (
      `${reactionCount} ${reactionCount === 1 ? 'reacción' : 'reacciones'} · ${commentCount} ${commentCount === 1 ? 'comentario' : 'comentarios'}`
    ),
  },
  en: {
    featured: 'Featured moment',
    publishing: 'Publishing…',
    connect: 'Connect',
    shortVideo: 'Short video',
    eventVideo: 'Event video',
    tapToOpen: 'Tap to open',
    imageLoadFailure: 'We could not load this photo',
    commentPlaceholder: 'Write a comment',
    sendComment: 'Send',
    errorTitle: 'We could not save the reaction',
    reactionFailure: 'Nothing changed in your account. Check your connection and try again.',
    viewPhoto: (authorName: string) => `View photo by ${authorName}`,
    openVideo: (authorName: string) => `Open video by ${authorName}`,
    sharedPhoto: (authorName: string) => `Photo shared by ${authorName}`,
    summary: (reactionCount: number, commentCount: number) => (
      `${reactionCount} ${reactionCount === 1 ? 'reaction' : 'reactions'} · ${commentCount} ${commentCount === 1 ? 'comment' : 'comments'}`
    ),
  },
} as const;

export const savedEventCopy = {
  es: {
    sessionExpired: 'Tu sesión terminó. Vuelve a iniciar sesión.',
    readyTitle: 'Listo',
    savedSuccess: 'Evento guardado en tu cuenta. Lo verás en tus otros dispositivos.',
    removedSuccess: 'Evento removido de los guardados de tu cuenta.',
    updateFailureTitle: 'No pudimos actualizar tus guardados',
    updateFailureBody: 'El cambio no se guardó en tu cuenta. Inténtalo nuevamente.',
    removeFailureTitle: 'No pudimos quitar el evento',
    signInTitle: 'Inicia sesión',
    signInBody: 'Necesitas una cuenta vinculada para guardar este evento y verlo en otros dispositivos.',
    signInSavedBody: 'Inicia sesión para ver y sincronizar tus eventos guardados.',
    signInSavedAccessibility: 'Ingresar para ver eventos guardados',
    later: 'Ahora no',
    signIn: 'Ingresar',
    loadFailureTitle: 'No pudimos cargar tus guardados',
    loadFailureBody: 'Comprueba tu sesión o conexión e inténtalo nuevamente.',
    retry: 'Reintentar',
    retrySavedAccessibility: 'Reintentar cargar eventos guardados',
    retrySavedDetailsAccessibility: 'Reintentar cargar los detalles de eventos guardados',
    saveAccessibility: 'Guardar evento en mi cuenta',
    removeAccessibility: 'Quitar evento de mis guardados',
    saveHint: 'Sincroniza este evento con los guardados de tu cuenta',
    saving: 'Guardando…',
    retrySaved: 'Reintentar guardados',
    loading: 'Cargando guardados…',
    saved: 'Guardado',
    save: 'Guardar evento',
    updating: 'Actualizando…',
    unavailable: 'Guardados no disponibles',
    saveShort: 'Guardar',
    cacheNotice: 'Mostramos la última lista confirmada en este dispositivo. Conéctate para actualizarla.',
    removeConfirmTitle: 'Quitar evento guardado',
    removeConfirmBody: '¿Quieres quitar este evento de tus guardados?',
    cancel: 'Cancelar',
    remove: 'Quitar',
    removeNamedAccessibility: (eventTitle: string) => `Quitar ${eventTitle} de mis eventos guardados`,
    importTitle: 'Encontramos guardados de esta cuenta en este dispositivo',
    importBody: 'Impórtalos para verlos en tus otros dispositivos.',
    importLaterAccessibility: 'Importar eventos guardados más tarde',
    importAccessibility: 'Importar eventos guardados a mi cuenta',
    importing: 'Importando…',
    import: 'Importar',
    importSuccessTitle: 'Guardados importados',
    importSuccess: (count: number) => count === 1
      ? 'Importamos 1 evento a tu cuenta.'
      : `Importamos ${count} eventos a tu cuenta.`,
    importFailureTitle: 'Importación incompleta',
    importFailure: (importedCount: number, totalCount: number) => (
      `Importamos ${importedCount} de ${totalCount} eventos. No borramos la copia de este dispositivo. Inténtalo nuevamente.`
    ),
    importFailureFallback: 'No borramos la copia de este dispositivo. Inténtalo nuevamente.',
    pendingImportFailure: 'No pudimos leer los guardados pendientes. La copia de este dispositivo quedó intacta.',
    savedTabAccessibility: 'Eventos guardados',
    showSavedAccessibility: 'Mostrar eventos guardados',
    savedTab: 'Guardados',
    savedEmpty: 'Aún no hay eventos guardados. Toca Guardar evento dentro de cualquier evento.',
    savedTitle: (count: number) => `Eventos guardados (${count})`,
    someUnavailable: 'Algunos eventos guardados ya no están disponibles o no pudieron cargarse.',
    detailsUnavailable: 'No pudimos mostrar los detalles de tus eventos guardados. Reintenta cuando tengas conexión.',
    savedDateEmpty: 'No hay eventos guardados en esta fecha',
    savedListEmpty: 'No se encontraron eventos guardados',
  },
  en: {
    sessionExpired: 'Your session ended. Log in again.',
    readyTitle: 'Done',
    savedSuccess: 'Event saved to your account. You will see it on your other devices.',
    removedSuccess: 'Event removed from your account’s saved events.',
    updateFailureTitle: 'We could not update your saved events',
    updateFailureBody: 'The change was not saved to your account. Try again.',
    removeFailureTitle: 'We could not remove the event',
    signInTitle: 'Log in',
    signInBody: 'You need a linked account to save this event and see it on your other devices.',
    signInSavedBody: 'Log in to view and sync your saved events.',
    signInSavedAccessibility: 'Log in to view saved events',
    later: 'Not now',
    signIn: 'Log in',
    loadFailureTitle: 'We could not load your saved events',
    loadFailureBody: 'Check your session or connection and try again.',
    retry: 'Try again',
    retrySavedAccessibility: 'Try loading saved events again',
    retrySavedDetailsAccessibility: 'Try loading saved event details again',
    saveAccessibility: 'Save event to my account',
    removeAccessibility: 'Remove event from my saved events',
    saveHint: 'Syncs this event with your account’s saved events',
    saving: 'Saving…',
    retrySaved: 'Retry saved events',
    loading: 'Loading saved events…',
    saved: 'Saved',
    save: 'Save event',
    updating: 'Updating…',
    unavailable: 'Saved events unavailable',
    saveShort: 'Save',
    cacheNotice: 'Showing the last confirmed list on this device. Connect to refresh it.',
    removeConfirmTitle: 'Remove saved event',
    removeConfirmBody: 'Do you want to remove this event from your saved events?',
    cancel: 'Cancel',
    remove: 'Remove',
    removeNamedAccessibility: (eventTitle: string) => `Remove ${eventTitle} from my saved events`,
    importTitle: 'We found saved events for this account on this device',
    importBody: 'Import them to see them on your other devices.',
    importLaterAccessibility: 'Import saved events later',
    importAccessibility: 'Import saved events to my account',
    importing: 'Importing…',
    import: 'Import',
    importSuccessTitle: 'Saved events imported',
    importSuccess: (count: number) => count === 1
      ? 'We imported 1 event to your account.'
      : `We imported ${count} events to your account.`,
    importFailureTitle: 'Import incomplete',
    importFailure: (importedCount: number, totalCount: number) => (
      `We imported ${importedCount} of ${totalCount} events. We kept the copy on this device. Try again.`
    ),
    importFailureFallback: 'We kept the copy on this device. Try again.',
    pendingImportFailure: 'We could not read the pending saved events. The copy on this device is unchanged.',
    savedTabAccessibility: 'Saved events',
    showSavedAccessibility: 'Show saved events',
    savedTab: 'Saved',
    savedEmpty: 'No saved events yet. Tap Save event inside any event.',
    savedTitle: (count: number) => `Saved events (${count})`,
    someUnavailable: 'Some saved events are no longer available or could not be loaded.',
    detailsUnavailable: 'We could not show your saved event details. Try again when you are connected.',
    savedDateEmpty: 'No saved events on this date',
    savedListEmpty: 'No saved events found',
  },
} as const;

export const eventExperienceLanguage = onboardingLanguage;
