export const onboardingCopy = {
  es: {
    kicker: 'TDF Records',
    title: 'Tu comunidad musical, en un solo lugar',
    subtitle: 'Descubre eventos y conecta con los artistas que quieres seguir.',
    proofTitle: 'Empieza con algo útil hoy',
    proofBody: 'Explora eventos, guarda tus favoritos y sigue artistas. Te mostraremos el resto cuando lo necesites.',
    create: 'Crear cuenta',
    login: 'Ya tengo cuenta',
  },
  en: {
    kicker: 'TDF Records',
    title: 'Your music community, all in one place',
    subtitle: 'Discover events and connect with the artists you want to follow.',
    proofTitle: 'Start with something useful today',
    proofBody: 'Browse events, save favorites, and follow artists. We will introduce the rest when you need it.',
    create: 'Create account',
    login: 'I already have an account',
  },
} as const;

export const authCopy = {
  es: {
    createTitle: 'Crea tu cuenta', loginTitle: 'Inicia sesión', resetTitle: 'Restablecer contraseña',
    createSubtitle: 'Solo toma un minuto. Después continuaremos con lo que elegiste.',
    loginSubtitle: 'Accede a tus eventos, compras y códigos QR con tu cuenta de TDF Records.',
    resetSubtitle: 'Ingresa tu correo y te enviaremos un enlace para restablecer tu contraseña.',
    loginTab: 'Ingresar', signupTab: 'Crear cuenta', firstName: 'Nombre', lastName: 'Apellido', optional: 'opcional',
    firstNamePlaceholder: 'Tu nombre', lastNamePlaceholder: 'Tu apellido',
    email: 'Correo electrónico', emailPlaceholder: 'tu@correo.com', username: 'Usuario o correo',
    usernamePlaceholder: 'usuario o correo', password: 'Contraseña', currentPasswordPlaceholder: 'Tu contraseña',
    newPasswordPlaceholder: 'Mínimo 8 caracteres',
    passwordHint: 'Usa al menos 8 caracteres y como máximo 72 bytes UTF-8, sin caracteres de control ni formato oculto.',
    intentTitle: '¿Qué quieres hacer primero?',
    intentHint: 'Esto personaliza tu inicio; no solicita ni asigna permisos.',
    accept: 'Acepto los términos y la política de privacidad.', terms: 'Ver términos', privacy: 'Ver privacidad',
    marketing: 'Quiero recibir novedades de TDF (opcional).', create: 'Crear cuenta y continuar',
    login: 'Ingresar', googleCreate: 'Crear cuenta con Google', googleLogin: 'Continuar con Google',
    show: 'Mostrar contraseña', hide: 'Ocultar contraseña', invalidEmail: 'Ingresa un correo electrónico válido.',
    forgot: '¿Olvidaste tu contraseña?', divider: 'o', sendReset: 'Enviar enlace', backToLogin: 'Volver al inicio de sesión',
    resetSuccess: 'Si el correo está registrado, te enviamos un enlace para restablecer tu contraseña. Revisa tu bandeja de entrada.',
    resetFailure: 'No pudimos enviar el enlace. Verifica el correo.',
    loginSuccess: 'Sesión iniciada.', loginFailure: 'No pudimos iniciar sesión.',
    signupSuccess: 'Cuenta creada. Continuemos con lo que elegiste.', signupFailure: 'No pudimos crear tu cuenta.',
    googleSuccess: 'Sesión con Google iniciada.', googleCancelled: 'Inicio con Google cancelado.',
    googleMissingToken: 'Google no devolvió un idToken válido.', googleInProgress: 'Google login ya está en progreso.',
    googleUnavailable: 'Google login requiere la build instalada de TDF Records; Expo Go no incluye Google Sign-In nativo.',
    googlePlayUnavailable: 'Google Play Services no está disponible en este dispositivo.', googleFailure: 'No pudimos iniciar sesión con Google.',
    sessionClosed: 'Sesión cerrada.', sessionStatus: 'Estado de sesión', sessionLoading: 'Cargando sesión guardada…',
    session: 'Sesión', sessionActive: 'Activa', sessionInactive: 'No iniciada', signOut: 'Cerrar sesión',
  },
  en: {
    createTitle: 'Create your account', loginTitle: 'Log in', resetTitle: 'Reset password',
    createSubtitle: 'It only takes a minute. Then we will continue with what you chose.',
    loginSubtitle: 'Access your events, purchases, and QR codes with your TDF Records account.',
    resetSubtitle: 'Enter your email and we will send you a password reset link.',
    loginTab: 'Log in', signupTab: 'Create account', firstName: 'First name', lastName: 'Last name', optional: 'optional',
    firstNamePlaceholder: 'Your first name', lastNamePlaceholder: 'Your last name',
    email: 'Email', emailPlaceholder: 'you@example.com', username: 'Username or email',
    usernamePlaceholder: 'username or email', password: 'Password', currentPasswordPlaceholder: 'Your password',
    newPasswordPlaceholder: 'At least 8 characters',
    passwordHint: 'Use at least 8 characters and at most 72 UTF-8 bytes, with no control or hidden formatting characters.',
    intentTitle: 'What do you want to do first?',
    intentHint: 'This personalizes your start; it does not request or assign permissions.',
    accept: 'I accept the terms and privacy policy.', terms: 'View terms', privacy: 'View privacy',
    marketing: 'I want to receive TDF updates (optional).', create: 'Create account and continue',
    login: 'Log in', googleCreate: 'Create account with Google', googleLogin: 'Continue with Google',
    show: 'Show password', hide: 'Hide password', invalidEmail: 'Enter a valid email address.',
    forgot: 'Forgot your password?', divider: 'or', sendReset: 'Send link', backToLogin: 'Back to login',
    resetSuccess: 'If the email is registered, we sent a password reset link. Check your inbox.',
    resetFailure: 'We could not send the link. Check the email address.',
    loginSuccess: 'You are logged in.', loginFailure: 'We could not log you in.',
    signupSuccess: 'Account created. Let’s continue with what you chose.', signupFailure: 'We could not create your account.',
    googleSuccess: 'You are signed in with Google.', googleCancelled: 'Google sign-in cancelled.',
    googleMissingToken: 'Google did not return a valid idToken.', googleInProgress: 'Google sign-in is already in progress.',
    googleUnavailable: 'Google sign-in requires the installed TDF Records build; Expo Go does not include native Google Sign-In.',
    googlePlayUnavailable: 'Google Play Services is unavailable on this device.', googleFailure: 'We could not sign you in with Google.',
    sessionClosed: 'Signed out.', sessionStatus: 'Session status', sessionLoading: 'Loading saved session…',
    session: 'Session', sessionActive: 'Active', sessionInactive: 'Not signed in', signOut: 'Sign out',
  },
} as const;

export const experimentCopy = {
  es: {
    eyebrow: 'Bienvenido a TDF', eventFallback: 'el próximo evento', titleFallback: 'Vive el primer momento',
    subtitle: 'Reacciona a un momento para empezar. Es la forma más rápida de sentir la vibra.',
    loading: 'Cargando momentos',
    offlineTitle: 'Estás sin conexión', offlineBody: 'Conéctate para cargar momentos o continúa a eventos guardados.',
    errorTitle: 'No pudimos cargar los momentos', errorBody: 'Revisa tu conexión o continúa a eventos. Puedes volver a intentarlo desde allí.',
    reactionsUnavailable: 'Sin reacciones sincronizadas. Actualiza los catálogos para reaccionar.',
    emptyTitle: 'Aún no hay momentos publicados',
    emptyBody: 'Cuando alguien suba el primer momento del evento lo verás aquí. Mientras tanto, explora eventos, tickets, transmisiones y clubes de fans.',
    previewLabel: 'Mientras esperas', previewBody: 'Descubre lo que viene y guarda tus eventos favoritos.', explore: 'Ver eventos',
  },
  en: {
    eyebrow: 'Welcome to TDF', eventFallback: 'the next event', titleFallback: 'Experience your first moment',
    subtitle: 'React to a moment to get started. It is the fastest way to feel the energy.',
    loading: 'Loading moments',
    offlineTitle: 'You are offline', offlineBody: 'Connect to load moments or continue to saved events.',
    errorTitle: 'We could not load moments', errorBody: 'Check your connection or continue to events. You can try again there.',
    reactionsUnavailable: 'Reactions are not synchronized. Refresh catalogs to react.',
    emptyTitle: 'No moments have been posted yet',
    emptyBody: 'When someone posts the event’s first moment, you will see it here. Meanwhile, explore events, tickets, streams, and fan clubs.',
    previewLabel: 'While you wait', previewBody: 'Discover what is coming and save your favorite events.', explore: 'View events',
  },
} as const;

export const onboardingLanguage = (locale: string): 'es' | 'en' => locale.startsWith('en') ? 'en' : 'es';
